import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import GradientBackground from "@/components/ui-engineer/layout/gradient-background";
import { Spotlight } from "@/components/aceternity/spotlight-new";
import { Tomorrow } from "next/font/google";
import { ContributionGraphProvider } from "@/context/cg-context";
import { Header } from "@/components/ui-engineer/layout/header";
import { Footer } from "@/components/ui-engineer/layout/footer";
import { MusicPlayer } from "@/components/ui-engineer/layout/music-player";

const tomorrow = Tomorrow({
   subsets: ["latin"],
   variable: "--font-tomorrow",
   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
   style: ["normal", "italic"],
   display: "swap",
});

export const metadata: Metadata = {
   title: "E-Learning",
   description: "Generated by NV-Phong",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={`${tomorrow.variable} antialiased scrollbar-hide selection:bg`}
         suppressHydrationWarning
      >
         <body>
            <ThemeProvider
               attribute="class"
               defaultTheme="light"
               enableSystem
               disableTransitionOnChange
               themes={["light", "dark", "pastel-pink"]}
            >
               <ContributionGraphProvider>
                  <Spotlight />
                  <Header />
                  {children}
                  <Footer />
                  <MusicPlayer></MusicPlayer>
                  <GradientBackground />
               </ContributionGraphProvider>
            </ThemeProvider>
            <Analytics />
            <SpeedInsights />
         </body>
      </html>
   );
}
